# Generated by Django 3.2.8 on 2021-11-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20211118_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
