# Generated by Django 3.2.8 on 2021-11-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_public_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_url',
            field=models.CharField(blank=True, default='', max_length=250, unique=True),
        ),
    ]
