# Generated by Django 3.2.8 on 2021-11-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20211125_0431'),
        ('authentication', '0014_user_friends'),
    ]

    operations = [
    ]
