# Generated by Django 3.0.4 on 2021-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_0014_auto_20211125_0431_0014_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpvalidation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
