# Generated by Django 3.2.8 on 2021-10-26 03:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookSelf',
            new_name='BookShelf',
        ),
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name': 'Book Shelf', 'verbose_name_plural': 'Book Shelf'},
        ),
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together={('book_id', 'user_id')},
        ),
        migrations.AlterModelTable(
            name='bookshelf',
            table='book_shelf',
        ),
    ]
