# Generated by Django 3.2.8 on 2021-10-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211026_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='search_info',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
