# Generated by Django 3.2.8 on 2021-10-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='user_id',
            new_name='user',
        ),
    ]
