# Generated by Django 3.2.8 on 2021-10-26 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_auto_20211026_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book_in_self',
            new_name='book_in_shelf',
        ),
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together={('book_id', 'user_id')},
        ),
    ]
