# Generated by Django 3.2.8 on 2021-10-26 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_auto_20211026_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together={('book_id', 'user_id')},
        ),
    ]
