# Generated by Django 3.2.8 on 2021-10-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20211026_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='user_id',
            new_name='user',
        ),
    ]
