# Generated by Django 3.2.8 on 2021-10-27 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_auto_20211026_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='book_in_shelf',
            field=models.CharField(choices=[('RL', 'Readlist'), ('WL', 'Wishlist'), ('SL', 'Selflist')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together={('book_id', 'user_id')},
        ),
    ]
