# Generated by Django 3.2.8 on 2021-10-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20211027_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='book_in_shelf',
            field=models.CharField(choices=[('RL', 'Readlist'), ('WL', 'Wishlist'), ('SL', 'Selflist')], default='RL', max_length=2),
        ),
    ]
