# Generated by Django 3.0.4 on 2021-11-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_bookseoid'),
        ('books', '0016_auto_20211116_0418'),
    ]

    operations = [
    ]
