# Generated by Django 3.0.4 on 2021-11-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20211117_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseoid',
            name='book',
        ),
        migrations.AddField(
            model_name='bookseoid',
            name='bookid',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
