# Generated by Django 3.0.4 on 2021-11-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20211117_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSeoid',
        ),
    ]
