# Generated by Django 3.2.8 on 2021-11-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20211118_0412'),
        ('books', '0021_delete_bookseoid'),
    ]

    operations = [
    ]
