# Generated by Django 3.2.8 on 2021-11-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_merge_0021_auto_20211118_0412_0021_delete_bookseoid'),
        ('books', '0022_merge_20211119_0515'),
    ]

    operations = [
    ]
