# Generated by Django 3.2.8 on 2021-11-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_merge_20211119_1331'),
        ('books', '0023_merge_20211122_0500'),
    ]

    operations = [
    ]
